import { saveAs } from 'file-saver';
import * as XLSX from 'xlsx';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

/**
 * Export data to Excel (.xlsx)
 */
export const exportToExcel = (data: any[], fileName: string) => {
  const worksheet = XLSX.utils.json_to_sheet(data);
  const workbook = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(workbook, worksheet, 'Sheet1');
  const excelBuffer = XLSX.write(workbook, { bookType: 'xlsx', type: 'array' });
  const blob = new Blob([excelBuffer], { type: 'application/octet-stream' });
  
  // Create download link
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${fileName}.xlsx`;
  a.click();
  URL.revokeObjectURL(url);
};

/**
 * Export data to PDF
 */
export const exportToPDF = (headers: string[], data: any[][], fileName: string, title: string) => {
  const doc = new jsPDF();
  
  // Add title
  doc.setFontSize(18);
  doc.text(title, 14, 22);
  doc.setFontSize(11);
  doc.setTextColor(100);
  
  // Add date
  const date = new Date().toLocaleDateString();
  doc.text(`Generated on: ${date}`, 14, 30);

  autoTable(doc, {
    head: [headers],
    body: data,
    startY: 35,
    theme: 'grid',
    styles: { fontSize: 8, cellPadding: 2 },
    headStyles: { fillColor: [27, 67, 50], textColor: [255, 255, 255] }, // Dr. Ahmed Primary Color
  });

  doc.save(`${fileName}.pdf`);
};

/**
 * Export Prescription to PDF
 */
export const exportPrescriptionToPDF = (prescription: any, patientName: string) => {
  const doc = new jsPDF();
  
  // Header
  doc.setFontSize(22);
  doc.setTextColor(27, 67, 50); // Primary color
  doc.text('Dr. Ahmed Abdellatif', 14, 25);
  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text('Consultant of Urology & Andrology', 14, 32);
  
  // Divider
  doc.setDrawColor(27, 67, 50);
  doc.setLineWidth(0.5);
  doc.line(14, 40, 196, 40);

  // Patient Info
  doc.setFontSize(12);
  doc.setTextColor(0);
  doc.text(`Patient: ${patientName}`, 14, 50);
  doc.text(`Date: ${new Date(prescription.createdAt).toLocaleDateString()}`, 140, 50);

  // Diagnosis
  doc.setFontSize(14);
  doc.setTextColor(27, 67, 50);
  doc.text('Diagnosis', 14, 65);
  doc.setFontSize(11);
  doc.setTextColor(50);
  doc.text(prescription.diagnosisEn || prescription.diagnosisAr || 'N/A', 14, 73);

  // Rx Symbol
  doc.setFontSize(24);
  doc.setTextColor(0);
  doc.text('Rx', 14, 90);

  // Medications Table
  const medHeaders = ['Medication', 'Dosage', 'Duration', 'Notes'];
  const medData = prescription.medications.map((m: any) => [
    m.name,
    m.dosage,
    m.duration,
    m.notes || '-'
  ]);

  autoTable(doc, {
    head: [medHeaders],
    body: medData,
    startY: 95,
    theme: 'grid',
    styles: { fontSize: 10, cellPadding: 3 },
    headStyles: { fillColor: [240, 240, 240], textColor: [0, 0, 0], fontStyle: 'bold' },
  });

  // Instructions
  const finalY = (doc as any).lastAutoTable.finalY || 120;
  if (prescription.instructionsEn || prescription.instructionsAr) {
    doc.setFontSize(14);
    doc.setTextColor(27, 67, 50);
    doc.text('Instructions', 14, finalY + 15);
    doc.setFontSize(11);
    doc.setTextColor(50);
    doc.text(prescription.instructionsEn || prescription.instructionsAr, 14, finalY + 23);
  }

  // Footer
  const pageHeight = doc.internal.pageSize.height;
  doc.setFontSize(9);
  doc.setTextColor(150);
  doc.text('Generated by Dr. Ahmed Abdellatif Medical Platform', 14, pageHeight - 10);

  doc.save(`Prescription_${patientName.replace(/\s+/g, '_')}_${new Date().toISOString().split('T')[0]}.pdf`);
};
